apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-backend
  labels:
    app: java-maven-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-backend
  template:
    metadata:
      labels:
        app: java-maven-backend
    spec:
      containers:
        - name: java-maven-backend
          image: java-maven-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: " 512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 70
            periodSeconds: 20